### ISSUE TITLE
[Parent] Normal parent subscriptions

### ISSUE THREAD

**Issue by julianshutt** [vigour-io/state#116]
- [x] tests (similar to normal)
maybe add some reusability here?
- [x] reuse more functionality between $parent and parent
- [x] add .parent
- [x] combine with normal parent e.g. $parent + parent
- [x] in $parent need to do another check then [0] === '$'
- [x] references need to be handled specially ($c is not in subs so has to get attached to first common ancestor)
- [x] clean tree

need a normal parent subscription (like we had before) this is nest to $parent
```javascript
parent: { 
  val: true
}
```

**Comment by jimdebeer** [comment]
- [ ] tests (similair to normal)

**Comment by jimdebeer** [comment]
reuse more functionality between $parent and parent

**Comment by jimdebeer** [comment]
how to fix double ?

**Comment by jimdebeer** [comment]
since parent can go back to root trees its not sufficient to add $c segments until the parent
