### ISSUE TITLE
[Subscription] Features

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/state#13]
```javascript
$: {

 '*': {
     bla: 'xxxx'
  },
 '~': {
    x: true
  },
  'parent': {
    title: true
  },
  bla: {
    val: true // current implementation makes this fire for nested updates
  }
}
```

- [x] '*' collection
- [x] "true" leaf
- [x] "~" root
- [ ] "parent" parent
- [x] val

**Comment by jimdebeer** [comment]
@youzi what do you think of the val behavior?

**Comment by youzi** [comment]
I think it's useful. But, we do also need a way to subscribe more specifically.
Perhaps do `val` for specific subscription and something like `-r` for nested

**Comment by jimdebeer** [comment]
bit hard -- since it will become a separate track from the normal 'tree diffing algo' lets see if we really need this

**Comment by jimdebeer** [comment]
for now val subscribes deep by default -- cases where we have large objects on deeper level combined with primitives is small (non existing)
