### ISSUE TITLE
stamp is not a function

### ISSUE THREAD

**Issue by mstdokumaci** [vigour-io/state#135]
v4.4.0

Happens in the browser.
```js
const s = require('vigour-state/s')
module.exports = s({any: 'any'})
```
Throws:
`TypeError: stamp is not a function`
On this line of base/setKey:
`return this.properties[prop].call(this, val, stamp, resolve, nocontext, prop);`
Touches also this line of base constructor:
`this.set(val, stamp, true, true);`

After adding an empty function:
```js
module.exports = s({any: 'any'}, () => {})
```
Everything goes back to normal.

**Comment by jimdebeer** [comment]
cant recreate in the state repo where did this happen exactly?

**Comment by jimdebeer** [comment]
Issue moved to [vigour-io/ploy #4](https://github.com/vigour-io/ploy/issues/4) via [**ZenHub**](https://www.zenhub.com/)
