### ISSUE TITLE
[Spec]  state-tree

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/state#8]
requirements
- create a structure that allows for reuse of stamp values
- reuse as much as possible (not immutable, but same effect)
- fast insertion / lookup is essential
- for hub has to use keys
- for element has to use indices
- support a basic query language (subscriptions) that get hashed and shared and get a sub-state
- think about a possiblity to hash entire states (ultra fast communication)
- creation is the bottleneck, optimise for creation

**Comment by jimdebeer** [comment]
State is not a diffing alogrithm its a diff-manager

**proposed structure**
```javascript
{
   somefield: 654213, // stamp -- this means its a leaf (check r&b tree)
   bla: { $: 3213, otherfield: ... },
   something: { $: 45555, $i: { $r: [ 20, 50 ] , otherfied: 213231 },
    //if ordered (letters and chars can be ordered as well) by default inherits from parent
   blurgh: { field: 234234, $i: { $t: 'field' , $k: [ 'xxx', 'xyz', 0, 2]
}
```

**dictionary**
```
$i --> inherits
$k ---> keys
$r ----> range
$ ----> stamp
```

_optional_
```
$t  ---> type -- to add special handles e.g. properties stuff like that (prop not necessary)
```

**Comment by youzi** [comment]
**some notes:**
*on state:*
- one update fn: `.update(type, event)`
- for remove subscriptions: `hasRemoves:true` trinkles upward. 
- stop at node: `.hasWidgets` trinkles up (just use hasRemoves)

*on hub:*
- sync everything, client specifics on field client

**Comment by jimdebeer** [comment]
need the target in update as well (the observable your targeting)
